### ISSUE TITLE
Please update these two dependencies to the latest version

### ISSUE THREAD

**Issue by yanmastra** [tomykho/midtrans_sdk#13]
json_serializable: 
json_annotation:

**Comment by ariefsn** [comment]
@yanmastra 
try this
```yaml
  midtrans_sdk:
    git:
      url: https://github.com/ariefsn/midtrans_sdk
      ref: feature/update-deps

```
